### ISSUE TITLE
Dynamic source of default tabs

### ISSUE THREAD

**Issue by misbach** [york-solutions/fs-custom-tabs#2]
Let's dynamically fetch the list of default tabs that are available to install from this repo when the user hits the + tab. This will make it easy to manage the available tabs for those who have already installed the chrome extension.

**Comment by justincy** [comment]
I decided to go public. Using a gist was just a temporary solution while waiting to hear how you felt about going public. The downside of a gist is that I'm the only one who can update it.

**Comment by misbach** [comment]
yeah, I realized the gist updates would have to go through you. So I'm ok with it going public.
