### ISSUE TITLE
Support URL

### ISSUE THREAD

**Issue by misbach** [york-solutions/fs-custom-tabs#7]
I should've seen this coming. We need a Support URL in the support popup along with the phone, and email. So can we add a "support-url" to the manifest schema, and display that URL in the support pop-up?

**Comment by justincy** [comment]
Done, but it could take up to an hour for your extension to refresh the tab list and get the support URLs.

https://github.com/york-solutions/fs-custom-tabs/commit/5e91503426580ddd461723d275e6e47065a68dfb
