### ISSUE TITLE
Trello: Creating a list

### ISSUE THREAD

**Issue by misbach** [york-solutions/fs-custom-tabs#8]
It looks like a trello list is automatically created for a person when just viewing the Trello tab. We should not create a list until the user adds their first task. Is that doable?

**Comment by justincy** [comment]
Yeah, I've been aware of that. I almost tackled the problem but I don't think it's going to be fun so I decided against it. I'll do it.

**Comment by justincy** [comment]
By that I mean it's going to be a pain in the neck. There's a high probability that I'll have to rearchitect the whole thing. But at only 250 lines I guess that's not too bad.

**Comment by misbach** [comment]
Dang. Maybe it's not worth messing with at this time.

**Comment by justincy** [comment]
I just fixed it. Turns out I was being pessimistic. https://github.com/york-solutions/fs-custom-trello-tab/issues/1

**Comment by misbach** [comment]
🥇
